version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - /opt/frontend/node_modules
      - ./frontend:/opt/frontend/
    depends_on:
      - "backend"

  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:4000"
    volumes:
      - /opt/backend/node_modules
      - ./backend:/opt/backend